export const previewBaseUrl = "http://127.0.0.1:4173";

export const screenshotCaptures = [
  {
    id: "homepage-default",
    file: "homepage-default.png",
    route: "/?screenshot=1",
    size: "1440,2200",
    title: "Homepage Hero and Proof",
    surface: "site",
    purpose: "Top-of-README product impression and member-first value proposition.",
    priority: "primary",
  },
  {
    id: "member-home",
    file: "member-home.png",
    route: "/member-home.html?screenshot=1",
    size: "1440,1800",
    title: "Member Home",
    surface: "member",
    purpose: "Digest, alerts, and preference tuning in one frame.",
    priority: "primary",
  },
  {
    id: "admin-ops-board",
    file: "admin-ops-board.png",
    route: "/ops-board.html?screenshot=1",
    size: "1440,1900",
    title: "Admin Ops Board",
    surface: "admin",
    purpose: "Operational cockpit for reviews, health, and dispatch status.",
    priority: "primary",
  },
  {
    id: "lifecycle-state-lab",
    file: "lifecycle-state-lab.png",
    route: "/state-lab.html?screenshot=1",
    size: "1440,1600",
    title: "Lifecycle State Lab",
    surface: "cross-surface",
    purpose: "Shared lifecycle and state language across product surfaces.",
    priority: "primary",
  },
  {
    id: "homepage-empty-archive",
    file: "homepage-empty-archive.png",
    route: "/?state=empty&screenshot=1",
    size: "1440,2200",
    title: "Homepage Empty Archive State",
    surface: "site",
    purpose: "Secondary capture for empty-state review and delayed-publication messaging.",
    priority: "secondary",
  },
];
